# Generated by Django 2.0.9 on 2018-10-05 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number', models.CharField(max_length=200, verbose_name='Vin Number')),
                ('plate', models.CharField(max_length=200, verbose_name='Plate Number')),
                ('vehicle_type', models.CharField(choices=[('Trailer', 'TRAILER'), ('Truck', 'TRUCK')], default='TRUCK', max_length=7, verbose_name='Vehicle Type')),
                ('picture', models.ImageField(blank=True, max_length=200, null=True, upload_to='', verbose_name='Vehicle Picture')),
                ('fecha_creacion', models.DateField(blank=True, verbose_name='Date of purchase')),
            ],
        ),
    ]
