# Generated by Django 2.0.9 on 2018-10-05 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20181005_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('Regular', 'REGULAR'), ('Fix', 'FIX')], default='REGULAR', max_length=7, verbose_name='Maintenance Type')),
                ('cost', models.FloatField(verbose_name='Maintenance Cost')),
                ('maintenance_date', models.DateField(verbose_name='Maintenance Date')),
                ('description', models.TextField(verbose_name='Maintenance Description')),
            ],
        ),
        migrations.RenameField(
            model_name='vehicle',
            old_name='fecha_creacion',
            new_name='purchase_date',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('Ok', 'OK'), ('Damaged', 'DAMAGED'), ('Retired', 'RETIRED')], default='OK', max_length=7, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assets.Vehicle'),
        ),
    ]
