# Generated by Django 2.0.9 on 2018-10-06 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0003_auto_20181005_0453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField(max_length=15, verbose_name='Ammount')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField(max_length=15, verbose_name='Ammount')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=255, verbose_name='Order Number')),
                ('provider_company', models.CharField(max_length=255, verbose_name='Provider Company')),
                ('order_date', models.DateField(verbose_name='Order Date')),
                ('payed_miles', models.FloatField(max_length=15, verbose_name='Payed Miles')),
                ('start_miles', models.FloatField(blank=True, max_length=15, verbose_name='Starting Miles')),
                ('end_miles', models.FloatField(blank=True, max_length=15, verbose_name='Ending Miles')),
                ('delivery_date', models.DateField(blank=True, verbose_name='Delivery Date')),
                ('cost_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.Cost')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=20, verbose_name='Shipment Type')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20, verbose_name='State Name')),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.State'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='driver',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.ShipmentType'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='trailer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='trailer', to='assets.Vehicle'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='truck',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='truck', to='assets.Vehicle'),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='shipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.ShipmentType'),
        ),
        migrations.AddField(
            model_name='cost',
            name='shipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.ShipmentType'),
        ),
    ]
