# Generated by Django 2.0.9 on 2018-10-06 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toll_number', models.IntegerField(blank=True, verbose_name='Number of tolls')),
                ('toll_cost', models.FloatField(blank=True, max_length=15, verbose_name='Total Payed in tolls')),
                ('gas_gallons', models.FloatField(max_length=10, verbose_name='Number of Gas Gallons')),
                ('gas_cost', models.FloatField(max_length=10, verbose_name='Total Payed for Gas Gallons')),
                ('highlight', models.BooleanField(default=False, verbose_name='Did something went wrong?')),
                ('description', models.TextField(blank=True, verbose_name='Describe what went wrong')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.Shipment')),
            ],
        ),
    ]
