# Generated by Django 2.0.9 on 2018-10-06 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipmentcost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='end_date',
            field=models.DateField(default='2050-12-31', verbose_name='End Date'),
        ),
    ]
