# Generated by Django 2.0.9 on 2018-10-06 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_auto_20181006_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='start_miles',
            field=models.FloatField(blank=True, max_length=15, null=True, verbose_name='Starting Miles'),
        ),
    ]
