# Generated by Django 2.0.9 on 2018-10-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_auto_20181006_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='end_miles',
            field=models.FloatField(blank=True, max_length=15, null=True, verbose_name='Ending Miles'),
        ),
    ]
