# Generated by Django 2.0.9 on 2018-10-06 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_auto_20181006_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='end_miles',
            field=models.FloatField(blank=True, default=0, max_length=15, verbose_name='Ending Miles'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='start_miles',
            field=models.FloatField(blank=True, default=0, max_length=15, verbose_name='Starting Miles'),
        ),
        migrations.AlterField(
            model_name='shipmentcost',
            name='toll_cost',
            field=models.FloatField(blank=True, default=0, max_length=15, verbose_name='Total Payed in tolls'),
        ),
        migrations.AlterField(
            model_name='shipmentcost',
            name='toll_number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Number of tolls'),
        ),
    ]
