# Generated by Django 2.0.9 on 2018-10-08 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_auto_20181006_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentcost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shipmentcost',
            name='gas_cost',
        ),
        migrations.RemoveField(
            model_name='shipmentcost',
            name='highlight',
        ),
        migrations.RemoveField(
            model_name='shipmentcost',
            name='toll_cost',
        ),
        migrations.RemoveField(
            model_name='shipmentcost',
            name='toll_number',
        ),
        migrations.AddField(
            model_name='shipmentcost',
            name='cost',
            field=models.FloatField(default=0, max_length=10, verbose_name='Total Payed'),
        ),
        migrations.AddField(
            model_name='shipmentcost',
            name='expense_type',
            field=models.CharField(choices=[('Toll', 'TOLL'), ('Gas', 'Gas')], default='Gas', max_length=4, verbose_name='Expense Type'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='provider_company',
            field=models.CharField(default='Vandyville', editable=False, max_length=255, verbose_name='Provider Company'),
        ),
        migrations.AlterField(
            model_name='shipmentcost',
            name='gas_gallons',
            field=models.FloatField(max_length=10, verbose_name='If Gas, type in how many gallons'),
        ),
    ]
