# Generated by Django 2.0.9 on 2018-10-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_auto_20181008_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Has been payed?'),
        ),
        migrations.AlterField(
            model_name='shipmentcost',
            name='expense_type',
            field=models.CharField(choices=[('Toll', 'Toll'), ('Gas', 'Gas')], default='Gas', max_length=4, verbose_name='Expense Type'),
        ),
    ]
