# Generated by Django 2.0.9 on 2018-10-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_auto_20181008_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentcost',
            name='gas_gallons',
            field=models.FloatField(default=0, max_length=10, verbose_name='Gas Gallons'),
        ),
    ]
