# Generated by Django 2.0.9 on 2018-10-09 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_auto_20181008_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='cost_type',
        ),
        migrations.AddField(
            model_name='shipment',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Cost by mile'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='shipment_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='shipments.ShipmentType'),
        ),
    ]
