# Generated by Django 2.0.9 on 2018-10-11 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_auto_20181009_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payed_ammount', models.FloatField(max_length=15, verbose_name='Payed Ammount')),
                ('check_number', models.CharField(blank=True, max_length=255, unique=True, verbose_name='Check Number')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
            ],
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Order Number'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.Shipment'),
        ),
    ]
