# Generated by Django 2.0.9 on 2018-10-11 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_auto_20181011_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentcost',
            name='description',
            field=models.TextField(blank=True, verbose_name='Describe what went wrong'),
        ),
        migrations.AlterField(
            model_name='shipmentcost',
            name='expense_type',
            field=models.CharField(choices=[('Toll', 'Toll'), ('Gas', 'Gas'), ('Extra', 'Extra')], default='Gas', max_length=4, verbose_name='Expense Type'),
        ),
    ]
