# Generated by Django 2.0.9 on 2018-10-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_auto_20181011_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='payed_driver',
            field=models.BooleanField(default=False, verbose_name='Payed to Driver?'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Payed by client?'),
        ),
    ]
