# Generated by Django 2.0.9 on 2018-10-15 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0014_auto_20181011_0500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='start_miles',
            field=models.FloatField(max_length=15, verbose_name='Starting Miles'),
        ),
    ]
