# Generated by Django 2.0.9 on 2018-10-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0015_auto_20181015_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='shipment',
            name='order_picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
