# Generated by Django 2.0.9 on 2018-10-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0016_auto_20181015_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentcost',
            name='expense_type',
            field=models.CharField(choices=[('Toll', 'Toll'), ('Gas', 'Gas'), ('Extra', 'Extra')], default='Gas', max_length=5, verbose_name='Expense Type'),
        ),
    ]
