# Generated by Django 2.0.9 on 2018-10-16 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0018_shipmentcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='cost',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='shipments.ShipmentCompany'),
        ),
        migrations.AlterField(
            model_name='cost',
            name='shipment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.ShipmentType'),
        ),
    ]
