# Generated by Django 2.0.9 on 2018-10-17 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0020_auto_20181016_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='payed_driver_date',
            field=models.DateField(blank=True, null=True, verbose_name='Driver Payment Date'),
        ),
    ]
