# Generated by Django 2.0.9 on 2018-10-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0021_shipment_payed_driver_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='tandem',
            field=models.BooleanField(default=False, verbose_name='Tandem drivers?'),
        ),
    ]
