# Generated by Django 2.0.9 on 2018-10-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0023_shipment_last_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentcost',
            name='expense_type',
            field=models.CharField(choices=[('Toll', 'Toll'), ('Gas', 'Gas'), ('Extra', 'Extra'), ('Def', 'Def')], default='Gas', max_length=5, verbose_name='Expense Type'),
        ),
    ]
