# Generated by Django 2.0.9 on 2018-10-27 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0024_auto_20181027_2206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variation_type', models.CharField(choices=[('Bonus', 'BONUS'), ('Deduction', 'DEDUCTION')], default='BONUS', max_length=9, verbose_name='Variation Type')),
                ('ammount', models.FloatField(verbose_name='Maintenance Cost')),
                ('description', models.CharField(max_length=100, verbose_name='Description')),
                ('payment_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shipments.Payment')),
            ],
        ),
    ]
