# Generated by Django 2.0.9 on 2018-11-07 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0026_auto_20181107_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmentpicture',
            name='date',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Upload Date'),
        ),
    ]
