# Generated by Django 2.0.9 on 2018-11-08 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0028_auto_20181107_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='check_ammount',
        ),
        migrations.AddField(
            model_name='shipment',
            name='check_amount',
            field=models.FloatField(default=0, verbose_name='Check Amount'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='reconcile',
            field=models.BooleanField(default=False, verbose_name='Reconciled acount?'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tandem',
            field=models.BooleanField(default=False, verbose_name='Team drivers?'),
        ),
    ]
