# Generated by Django 2.0.9 on 2018-10-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181003_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='licence_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Licence Number'),
        ),
        migrations.AddField(
            model_name='user',
            name='licence_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='Licence Type'),
        ),
    ]
