# Generated by Django 2.0.9 on 2018-10-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181004_0211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='actual_picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='licence_picture',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to=''),
        ),
    ]
